import fs from 'fs';
import path from 'path';

const GALLERY_DIR = './public/The Gallery';
const OUTPUT_FILE = './src/galleryConfig.js';
const DEFAULT_ALBUMS = ['Classic', 'Wedding', 'Casual'];

function syncGallery() {
    console.log('--- Scanning Gallery Directory (Album-based) ---');
    try {
        if (!fs.existsSync(GALLERY_DIR)) {
            console.log(`Creating root gallery directory: ${GALLERY_DIR}`);
            fs.mkdirSync(GALLERY_DIR, { recursive: true });
        }

        // 1. Check for flat images in the root directory for migration
        const rootFiles = fs.readdirSync(GALLERY_DIR);
        const validExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
        
        const rootImages = rootFiles.filter(file => {
            const fullPath = path.join(GALLERY_DIR, file);
            if (fs.statSync(fullPath).isDirectory()) return false;
            const ext = path.extname(file).toLowerCase();
            return validExtensions.includes(ext);
        });

        if (rootImages.length > 0) {
            console.log(`Detected ${rootImages.length} flat images in the root. Migrating to default albums...`);
            
            // Create default folders
            DEFAULT_ALBUMS.forEach(album => {
                const albumPath = path.join(GALLERY_DIR, album);
                if (!fs.existsSync(albumPath)) {
                    fs.mkdirSync(albumPath, { recursive: true });
                }
            });

            // Distribute images
            rootImages.forEach((img, idx) => {
                const targetAlbum = DEFAULT_ALBUMS[idx % DEFAULT_ALBUMS.length];
                const oldPath = path.join(GALLERY_DIR, img);
                const newPath = path.join(GALLERY_DIR, targetAlbum, img);
                
                try {
                    fs.renameSync(oldPath, newPath);
                    console.log(`Moved: ${img} -> ${targetAlbum}/`);
                } catch (e) {
                    console.error(`Failed to move ${img}:`, e);
                }
            });
            console.log('Migration completed successfully!');
        }

        // 2. Scan for albums (subdirectories)
        const updatedFiles = fs.readdirSync(GALLERY_DIR);
        const albums = [];

        updatedFiles.forEach(file => {
            const fullPath = path.join(GALLERY_DIR, file);
            if (fs.statSync(fullPath).isDirectory()) {
                const albumName = file;
                const albumFiles = fs.readdirSync(fullPath);
                
                const images = albumFiles.filter(item => {
                    const ext = path.extname(item).toLowerCase();
                    return validExtensions.includes(ext);
                });

                // Sort numerically / alphabetically
                images.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

                albums.push({
                    name: albumName,
                    images: images
                });
            }
        });

        // Sort albums by name for consistency
        albums.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));

        console.log(`Found ${albums.length} albums: ${albums.map(a => `${a.name} (${a.images.length} imgs)`).join(', ')}`);

        // Construct the Javascript configuration content
        const fileContent = `// This file is automatically generated by update-gallery.js.
// Do not modify this file manually. Run "npm run sync-gallery" to update.

export const galleryAlbums = ${JSON.stringify(albums, null, 4)};
`;

        // Ensure target directory exists
        const outDir = path.dirname(OUTPUT_FILE);
        if (!fs.existsSync(outDir)) {
            fs.mkdirSync(outDir, { recursive: true });
        }

        // Write the configuration
        fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf-8');
        console.log(`Successfully generated config file at: ${OUTPUT_FILE}`);
        console.log('--- Sync Completed ---');
    } catch (error) {
        console.error('Error synchronizing gallery:', error);
    }
}

syncGallery();
