import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'
import sharp from 'sharp'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function regenerateGalleryConfig(dir) {
    const galleryDir = path.resolve(dir, './public/The Gallery');
    const outputFile = path.resolve(dir, './src/galleryConfig.js');
    if (!fs.existsSync(galleryDir)) return;
    
    const files = fs.readdirSync(galleryDir);
    const validExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
    const albums = [];

    files.forEach(file => {
        const fullPath = path.join(galleryDir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            const albumFiles = fs.readdirSync(fullPath);
            const images = albumFiles.filter(item => {
                const ext = path.extname(item).toLowerCase();
                return validExtensions.includes(ext);
            });
            images.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
            albums.push({
                name: file,
                images: images
            });
        }
    });

    albums.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));

    const fileContent = `// This file is automatically generated by update-gallery.js.
// Do not modify this file manually. Run "npm run sync-gallery" to update.

export const galleryAlbums = ${JSON.stringify(albums, null, 4)};
`;
    fs.writeFileSync(outputFile, fileContent, 'utf-8');
}

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        // API middleware plugin for gallery management
        {
            name: 'gallery-api',
            configureServer(server) {
                server.middlewares.use((req, res, next) => {
                    const galleryDir = path.resolve(__dirname, './public/The Gallery');
                    if (!fs.existsSync(galleryDir)) {
                        fs.mkdirSync(galleryDir, { recursive: true });
                    }

                    const parsedUrl = req.url.split('?')[0];

                    if (parsedUrl === '/api/gallery' && req.method === 'GET') {
                        try {
                            const files = fs.readdirSync(galleryDir);
                            const validExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
                            
                            let catalog = {};
                            const catalogPath = path.resolve(galleryDir, 'catalog.json');
                            if (fs.existsSync(catalogPath)) {
                                try {
                                    catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));
                                } catch (e) {
                                    console.error('Failed to parse local catalog:', e);
                                }
                            }

                            const albums = [];

                            files.forEach(file => {
                                const fullPath = path.join(galleryDir, file);
                                if (fs.statSync(fullPath).isDirectory()) {
                                    const albumFiles = fs.readdirSync(fullPath);
                                    
                                    // Group files into suits locally
                                    const suitMap = {};

                                    albumFiles.forEach(item => {
                                        const itemPath = path.join(fullPath, item);
                                        if (fs.statSync(itemPath).isDirectory()) {
                                            // It is a suit directory!
                                            const suitImages = fs.readdirSync(itemPath).filter(f => {
                                                const ext = path.extname(f).toLowerCase();
                                                return validExtensions.includes(ext);
                                            }).map(f => ({
                                                publicId: `ibrahim-aliraqi-gallery/${file}/${item}/${f}`,
                                                url: `/The Gallery/${file}/${item}/${f}`,
                                                filename: f
                                            }));

                                            if (suitImages.length > 0) {
                                                suitMap[item] = {
                                                    id: item,
                                                    isLegacy: false,
                                                    images: suitImages
                                                };
                                            }
                                        } else {
                                            // Legacy image directly in Category folder
                                            const ext = path.extname(item).toLowerCase();
                                            if (validExtensions.includes(ext)) {
                                                const suitId = item.replace(/\.[^/.]+$/, '').trim();
                                                if (!suitMap[suitId]) {
                                                    suitMap[suitId] = {
                                                        id: suitId,
                                                        isLegacy: true,
                                                        images: []
                                                    };
                                                }
                                                suitMap[suitId].images.push({
                                                    publicId: `ibrahim-aliraqi-gallery/${file}/${item}`,
                                                    url: `/The Gallery/${file}/${item}`,
                                                    filename: item
                                                });
                                            }
                                        }
                                    });

                                    // Map metadata to suits
                                    const suits = Object.values(suitMap).map(suit => {
                                        const key = suit.id.toLowerCase();
                                        const meta = catalog[key] || {};
                                        const cover = suit.images.find(img => img.filename.toLowerCase().startsWith('cover')) || suit.images[0];

                                        return {
                                            id: suit.id,
                                            nameAr: meta.ar?.name || '',
                                            nameEn: meta.en?.name || '',
                                            descAr: meta.ar?.desc || '',
                                            descEn: meta.en?.desc || '',
                                            priceAr: meta.ar?.price || '',
                                            priceEn: meta.en?.price || '',
                                            images: suit.images,
                                            coverImage: cover,
                                            isLegacy: suit.isLegacy
                                        };
                                    });

                                    // Sort suits: custom entries first, then legacy
                                    suits.sort((a, b) => {
                                        if (a.isLegacy && !b.isLegacy) return 1;
                                        if (!a.isLegacy && b.isLegacy) return -1;
                                        return a.id.localeCompare(b.id);
                                    });

                                    albums.push({ name: file, suits });
                                }
                            });

                            albums.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));

                            res.setHeader('Content-Type', 'application/json');
                            res.end(JSON.stringify({ albums, catalog }));
                        } catch (err) {
                            res.statusCode = 500;
                            res.end(JSON.stringify({ error: err.message }));
                        }

                    } else if (parsedUrl === '/api/upload' && req.method === 'POST') {
                        let bodyChunks = [];
                        req.on('data', chunk => { bodyChunks.push(chunk); });
                        req.on('end', async () => {
                            try {
                                const body = Buffer.concat(bodyChunks).toString();
                                 const { album, suitId, name, data } = JSON.parse(body);
                                if (!album) throw new Error('Album name is required');
                                const base64Data = data.replace(/^data:image\/\w+;base64,/, '');
                                const rawBuffer = Buffer.from(base64Data, 'base64');

                                // Compress to WebP: max 1920px wide, quality 82 (high visual quality, small file size)
                                const webpBuffer = await sharp(rawBuffer)
                                    .resize({ width: 1920, withoutEnlargement: true })
                                    .webp({ quality: 82, effort: 4 })
                                    .toBuffer();

                                // Save with .webp extension regardless of original format
                                const baseName = path.basename(name, path.extname(name));
                                const finalName = baseName + '.webp';

                                const targetAlbumDir = suitId 
                                    ? path.resolve(galleryDir, album, suitId) 
                                    : path.resolve(galleryDir, album);
                                if (!fs.existsSync(targetAlbumDir)) fs.mkdirSync(targetAlbumDir, { recursive: true });
                                fs.writeFileSync(path.resolve(targetAlbumDir, finalName), webpBuffer);

                                const origKB = Math.round(rawBuffer.length / 1024);
                                const compKB = Math.round(webpBuffer.length / 1024);
                                console.log(`[gallery-api] Uploaded: ${finalName} — ${origKB}KB → ${compKB}KB (WebP)`);

                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true, name: finalName, originalKB: origKB, compressedKB: compKB }));
                            } catch (err) {
                                console.error('[gallery-api] Upload error:', err);
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (parsedUrl === '/api/delete' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { album, suitId, name } = JSON.parse(body);
                                if (!album) throw new Error('Album name is required');
                                // Support nested suit subfolder
                                const targetPath = suitId 
                                    ? path.resolve(galleryDir, album, suitId, name)
                                    : path.resolve(galleryDir, album, name);
                                if (fs.existsSync(targetPath)) fs.unlinkSync(targetPath);
                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (parsedUrl === '/api/create-album' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { name } = JSON.parse(body);
                                if (!name) throw new Error('Album name is required');
                                const targetAlbumDir = path.resolve(galleryDir, name);
                                if (!fs.existsSync(targetAlbumDir)) fs.mkdirSync(targetAlbumDir, { recursive: true });
                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (parsedUrl === '/api/delete-album' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { name } = JSON.parse(body);
                                if (!name) throw new Error('Album name is required');
                                const targetAlbumDir = path.resolve(galleryDir, name);
                                if (fs.existsSync(targetAlbumDir)) fs.rmSync(targetAlbumDir, { recursive: true, force: true });
                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (parsedUrl === '/api/rename-album' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { oldName, newName } = JSON.parse(body);
                                if (!oldName || !newName) throw new Error('Old name and new name are required');
                                const oldPath = path.resolve(galleryDir, oldName);
                                const newPath = path.resolve(galleryDir, newName);
                                if (fs.existsSync(oldPath)) fs.renameSync(oldPath, newPath);
                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (parsedUrl === '/api/set-cover' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { album, suitId, filename } = JSON.parse(body);
                                if (!album || !filename) throw new Error('Album and filename are required');

                                // Support nested suit subfolder
                                const albumDir = suitId 
                                    ? path.resolve(galleryDir, album, suitId) 
                                    : path.resolve(galleryDir, album);
                                if (!fs.existsSync(albumDir)) fs.mkdirSync(albumDir, { recursive: true });

                                // 1. Find existing cover file in local directory and rename it to a timestamped name
                                const files = fs.readdirSync(albumDir);
                                files.forEach(file => {
                                    const baseName = path.basename(file, path.extname(file));
                                    if (baseName === 'cover') {
                                        const ext = path.extname(file);
                                        const oldPath = path.resolve(albumDir, file);
                                        const newPath = path.resolve(albumDir, `img_${Date.now()}${ext}`);
                                        fs.renameSync(oldPath, newPath);
                                    }
                                });

                                // 2. Rename the target file to 'cover.<ext>'
                                const ext = path.extname(filename);
                                const sourcePath = path.resolve(albumDir, filename);
                                const targetPath = path.resolve(albumDir, `cover${ext}`);
                                
                                if (fs.existsSync(sourcePath)) {
                                    fs.renameSync(sourcePath, targetPath);
                                }

                                regenerateGalleryConfig(__dirname);

                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (parsedUrl === '/api/move-image' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { fromAlbum, toAlbum, filename } = JSON.parse(body);
                                if (!fromAlbum || !toAlbum || !filename) throw new Error('Missing parameters');

                                const sourcePath = path.resolve(galleryDir, fromAlbum, filename);
                                const targetDir = path.resolve(galleryDir, toAlbum);
                                const targetPath = path.resolve(targetDir, filename);

                                if (!fs.existsSync(targetDir)) {
                                    fs.mkdirSync(targetDir, { recursive: true });
                                }

                                if (fs.existsSync(sourcePath)) {
                                    fs.renameSync(sourcePath, targetPath);
                                    console.log(`[gallery-api] Moved file: ${filename} from ${fromAlbum} to ${toAlbum}`);
                                }

                                regenerateGalleryConfig(__dirname);

                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (parsedUrl === '/api/update-product' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { filename, metadata } = JSON.parse(body);
                                if (!filename || !metadata) throw new Error('Missing parameters');

                                const catalogPath = path.resolve(galleryDir, 'catalog.json');
                                let catalog = {};
                                if (fs.existsSync(catalogPath)) {
                                    try {
                                        catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));
                                    } catch (e) {}
                                }

                                const key = filename.toLowerCase().replace(/\.[^/.]+$/, '').trim();
                                catalog[key] = {
                                    en: {
                                        name: metadata.nameEn || '',
                                        desc: metadata.descEn || '',
                                        price: metadata.priceEn || ''
                                    },
                                    ar: {
                                        name: metadata.nameAr || '',
                                        desc: metadata.descAr || '',
                                        price: metadata.priceAr || ''
                                    }
                                };

                                fs.writeFileSync(catalogPath, JSON.stringify(catalog, null, 2), 'utf8');
                                console.log(`[gallery-api] Updated local product details for ${key}`);

                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (parsedUrl === '/api/auth' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { password } = JSON.parse(body);
                                // In dev mode: accept any password if ADMIN_PASSWORD is not set,
                                // or validate against the env var
                                const adminPw = process.env.ADMIN_PASSWORD;
                                const ok = !adminPw || password === adminPw;
                                res.setHeader('Content-Type', 'application/json');
                                if (ok) {
                                    res.end(JSON.stringify({ success: true }));
                                } else {
                                    res.statusCode = 401;
                                    res.end(JSON.stringify({ error: 'Invalid password' }));
                                }
                            } catch (err) {
                                res.statusCode = 400;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else {
                        next();
                    }
                });
            }
        }
    ],
    resolve: {
        alias: {
            "@": path.resolve(__dirname, "./src"),
        },
    },
    build: {
        rollupOptions: {
            output: {
                manualChunks: {
                    'vendor-react': ['react', 'react-dom'],
                    'vendor-framer': ['framer-motion'],
                    'vendor-gsap': ['gsap'],
                },
            },
        },
    },
})
