import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'
import sharp from 'sharp'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function regenerateGalleryConfig(dir) {
    const galleryDir = path.resolve(dir, './public/The Gallery');
    const outputFile = path.resolve(dir, './src/galleryConfig.js');
    if (!fs.existsSync(galleryDir)) return;
    
    const files = fs.readdirSync(galleryDir);
    const validExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
    const albums = [];

    files.forEach(file => {
        const fullPath = path.join(galleryDir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            const albumFiles = fs.readdirSync(fullPath);
            const images = albumFiles.filter(item => {
                const ext = path.extname(item).toLowerCase();
                return validExtensions.includes(ext);
            });
            images.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
            albums.push({
                name: file,
                images: images
            });
        }
    });

    albums.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));

    const fileContent = `// This file is automatically generated by update-gallery.js.
// Do not modify this file manually. Run "npm run sync-gallery" to update.

export const galleryAlbums = ${JSON.stringify(albums, null, 4)};
`;
    fs.writeFileSync(outputFile, fileContent, 'utf-8');
}

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        // API middleware plugin for gallery management
        {
            name: 'gallery-api',
            configureServer(server) {
                server.middlewares.use((req, res, next) => {
                    const galleryDir = path.resolve(__dirname, './public/The Gallery');
                    if (!fs.existsSync(galleryDir)) {
                        fs.mkdirSync(galleryDir, { recursive: true });
                    }

                    if (req.url === '/api/gallery' && req.method === 'GET') {
                        try {
                            const files = fs.readdirSync(galleryDir);
                            const validExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
                            const albums = [];

                            files.forEach(file => {
                                const fullPath = path.join(galleryDir, file);
                                if (fs.statSync(fullPath).isDirectory()) {
                                    const albumFiles = fs.readdirSync(fullPath);
                                    const images = albumFiles.filter(item => {
                                        const ext = path.extname(item).toLowerCase();
                                        return validExtensions.includes(ext);
                                    });
                                    images.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
                                    albums.push({ name: file, images });
                                }
                            });

                            albums.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));

                            res.setHeader('Content-Type', 'application/json');
                            res.end(JSON.stringify({ albums }));
                        } catch (err) {
                            res.statusCode = 500;
                            res.end(JSON.stringify({ error: err.message }));
                        }

                    } else if (req.url === '/api/upload' && req.method === 'POST') {
                        let bodyChunks = [];
                        req.on('data', chunk => { bodyChunks.push(chunk); });
                        req.on('end', async () => {
                            try {
                                const body = Buffer.concat(bodyChunks).toString();
                                const { album, name, data } = JSON.parse(body);
                                if (!album) throw new Error('Album name is required');
                                const base64Data = data.replace(/^data:image\/\w+;base64,/, '');
                                const rawBuffer = Buffer.from(base64Data, 'base64');

                                // Compress to WebP: max 1920px wide, quality 82 (high visual quality, small file size)
                                const webpBuffer = await sharp(rawBuffer)
                                    .resize({ width: 1920, withoutEnlargement: true })
                                    .webp({ quality: 82, effort: 4 })
                                    .toBuffer();

                                // Save with .webp extension regardless of original format
                                const baseName = path.basename(name, path.extname(name));
                                const finalName = baseName + '.webp';

                                const targetAlbumDir = path.resolve(galleryDir, album);
                                if (!fs.existsSync(targetAlbumDir)) fs.mkdirSync(targetAlbumDir, { recursive: true });
                                fs.writeFileSync(path.resolve(targetAlbumDir, finalName), webpBuffer);

                                const origKB = Math.round(rawBuffer.length / 1024);
                                const compKB = Math.round(webpBuffer.length / 1024);
                                console.log(`[gallery-api] Uploaded: ${finalName} — ${origKB}KB → ${compKB}KB (WebP)`);

                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true, name: finalName, originalKB: origKB, compressedKB: compKB }));
                            } catch (err) {
                                console.error('[gallery-api] Upload error:', err);
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (req.url === '/api/delete' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { album, name } = JSON.parse(body);
                                if (!album) throw new Error('Album name is required');
                                const targetPath = path.resolve(galleryDir, album, name);
                                if (fs.existsSync(targetPath)) fs.unlinkSync(targetPath);
                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (req.url === '/api/create-album' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { name } = JSON.parse(body);
                                if (!name) throw new Error('Album name is required');
                                const targetAlbumDir = path.resolve(galleryDir, name);
                                if (!fs.existsSync(targetAlbumDir)) fs.mkdirSync(targetAlbumDir, { recursive: true });
                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (req.url === '/api/delete-album' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { name } = JSON.parse(body);
                                if (!name) throw new Error('Album name is required');
                                const targetAlbumDir = path.resolve(galleryDir, name);
                                if (fs.existsSync(targetAlbumDir)) fs.rmSync(targetAlbumDir, { recursive: true, force: true });
                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (req.url === '/api/rename-album' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { oldName, newName } = JSON.parse(body);
                                if (!oldName || !newName) throw new Error('Old name and new name are required');
                                const oldPath = path.resolve(galleryDir, oldName);
                                const newPath = path.resolve(galleryDir, newName);
                                if (fs.existsSync(oldPath)) fs.renameSync(oldPath, newPath);
                                regenerateGalleryConfig(__dirname);
                                res.setHeader('Content-Type', 'application/json');
                                res.end(JSON.stringify({ success: true }));
                            } catch (err) {
                                res.statusCode = 500;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else if (req.url === '/api/auth' && req.method === 'POST') {
                        let body = '';
                        req.on('data', chunk => { body += chunk; });
                        req.on('end', () => {
                            try {
                                const { password } = JSON.parse(body);
                                // In dev mode: accept any password if ADMIN_PASSWORD is not set,
                                // or validate against the env var
                                const adminPw = process.env.ADMIN_PASSWORD;
                                const ok = !adminPw || password === adminPw;
                                res.setHeader('Content-Type', 'application/json');
                                if (ok) {
                                    res.end(JSON.stringify({ success: true }));
                                } else {
                                    res.statusCode = 401;
                                    res.end(JSON.stringify({ error: 'Invalid password' }));
                                }
                            } catch (err) {
                                res.statusCode = 400;
                                res.end(JSON.stringify({ error: err.message }));
                            }
                        });

                    } else {
                        next();
                    }
                });
            }
        }
    ],
    resolve: {
        alias: {
            "@": path.resolve(__dirname, "./src"),
        },
    },
    build: {
        rollupOptions: {
            output: {
                manualChunks: {
                    'vendor-react': ['react', 'react-dom'],
                    'vendor-framer': ['framer-motion'],
                    'vendor-gsap': ['gsap'],
                },
            },
        },
    },
})
