// This file is automatically generated by update-gallery.js.
// Do not modify this file manually. Run "npm run sync-gallery" to update.

export const galleryAlbums = [
    {
        "name": "Classic",
        "images": [
            "cover.jpeg",
            "IMG_0201.JPG.jpeg",
            "IMG_0205.JPG.jpeg",
            "IMG_0207.JPG.jpeg",
            "IMG_0233.JPG.jpeg",
            "IMG_0261.JPG.jpeg",
            "IMG_0262.JPG.jpeg",
            "IMG_0263.JPG.jpeg",
            "IMG_0274.JPG.jpeg",
            "IMG_0324.JPG.jpeg",
            "IMG_0338.JPG.jpeg",
            "IMG_0339.JPG.jpeg",
            "IMG_0347.JPG.jpeg",
            "IMG_0360.JPG.jpeg",
            "IMG_0362.JPG.jpeg",
            "IMG_0368.JPG.jpeg",
            "IMG_0369.JPG.jpeg",
            "IMG_0382.JPG.jpeg",
            "IMG_0384.JPG.jpeg",
            "IMG_0394.JPG.jpeg",
            "IMG_0395.JPG.jpeg",
            "IMG_0397.JPG.jpeg",
            "IMG_0399.JPG.jpeg"
        ]
    }
];
